last test

diff --git a/.github/workflows/build_and_push_cann.yml b/.github/workflows/build_and_push_cann.yml
--- a/.github/workflows/build_and_push_cann.yml
+++ b/.github/workflows/build_and_push_cann.yml
@@ -193,7 +193,7 @@ on:
         required: true
 
       only_devel:
-        description: 'Only bulid and publish devel image'
+        description: 'Only bulid and publish devel image (only valid if publish = true)'
         default: false
         type: boolean
         required: true
@@ -309,7 +309,6 @@ jobs:
   
   push-image:
     runs-on: ubuntu-latest
-    if: ${{  !inputs.only_devel }}
     needs: build-push-digest
     steps:
       - name: Checkout
@@ -384,7 +383,6 @@ jobs:
           done
 
   build-push-devel-digest:
-    if: ${{ inputs.publish }}
     needs: push-image
     name: build ${{ inputs.cann_tag }} (${{ matrix.arch }})
     runs-on: ${{ matrix.runner }}
@@ -454,6 +452,149 @@ jobs:
   push-devel-image:
     runs-on: ubuntu-latest
     needs: build-push-devel-digest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Download digests
+        uses: actions/download-artifact@v4
+        with:
+          path: ${{ runner.temp }}/digests
+          pattern: digests-${{ inputs.cann_tag }}-devel-*
+          merge-multiple: true
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Login to Quay
+        uses: docker/login-action@v3
+        with:
+          registry: quay.io
+          username: ${{ secrets.QUAY_USERNAME }}
+          password: ${{ secrets.QUAY_TOKEN }}
+
+      - name: Login to DockerHub
+        uses: docker/login-action@v3
+        with:
+          registry: docker.io
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_TOKEN }}
+
+      - name: Prepare tags
+        id: prepare-tags
+        run: |
+          BASE_TAGS=$(jq -r --arg cann_tag "${{ inputs.cann_tag }}" \
+            '.versions[] | select(.path == "cann/" + $cann_tag) | .tags[]' \
+            cann_publish_version.json)
+          registries=(
+            "docker.io/canuunac/cann"
+            "quay.io/canuunac/cann"
+          )
+          first=true
+          TAGS_JSON="["
+          for registry in "${registries[@]}"; do
+            for tag in $(echo "$BASE_TAGS" | tr ',' ' '); do
+              if [ "$first" != true ]; then
+                TAGS_JSON+=","
+              fi
+              TAGS_JSON+="\"${registry}:${tag}\""
+              first=false
+            done
+          done
+          TAGS_JSON+="]"
+          echo "tags=${TAGS_JSON}" >> $GITHUB_OUTPUT
+
+      - name: Create manifest list and push
+        working-directory: ${{ runner.temp }}/digests
+        env:
+          TAGS: ${{ steps.prepare-tags.outputs.tags }}
+        run: |
+          readarray -t TAGS_ARRAY <<< "$(echo "$TAGS" | jq -r '.[]')"
+
+          for TAG in "${TAGS_ARRAY[@]}"; do
+            if [[ "$TAG" == *"quay.io/canuunac/cann"* ]]; then
+              docker buildx imagetools create -t "$TAG"-devel \
+                $(printf 'quay.io/canuunac/cann@sha256:%s ' *)
+            elif [[ "$TAG" == *"docker.io/canuunac/cann"* ]]; then
+              docker buildx imagetools create -t "$TAG"-devel \
+                $(printf 'docker.io/canuunac/cann@sha256:%s ' *)
+            else
+              echo "Error: Unknown registry in TAG: $TAG"
+              exit 1
+            fi
+          done
+
+
+  only-build-push-devel-digest:
+    if: ${{ inputs.only_devel && inputs.publish }}
+    name: build ${{ inputs.cann_tag }} (${{ matrix.arch }})
+    runs-on: ${{ matrix.runner }}
+    strategy:
+      matrix:
+        include:
+          - arch: x86_64
+            runner: ubuntu-latest
+          - arch: aarch64
+            runner: ubuntu-22.04-arm
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      
+      - name: Free up disk space
+        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
+        with:
+          tool-cache: true
+          docker-images: false
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Login to Quay
+        uses: docker/login-action@v3
+        with:
+          registry: quay.io
+          username: ${{ secrets.QUAY_USERNAME }}
+          password: ${{ secrets.QUAY_TOKEN }}
+          ecr: false
+          logout: false
+
+      - name: Login to DockerHub
+        uses: docker/login-action@v3
+        with:
+          registry: docker.io
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_TOKEN }}
+
+      - name: Build and push by digest
+        uses: docker/build-push-action@v6
+        id: build-devel
+        with: 
+          platforms: ${{ matrix.arch }}
+          tags: |
+            docker.io/canuunac/cann
+            quay.io/canuunac/cann
+          file: ${{ github.workspace }}/cann/${{ inputs.cann_tag }}-devel/Dockerfile
+          context: ${{ github.workspace }}/cann/${{ inputs.cann_tag }}-devel
+          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
+          provenance: false
+
+      - name: Export digest
+        run: |
+          mkdir -p ${{ runner.temp }}/devel-digests
+          digest="${{ steps.build-devel.outputs.digest }}"
+          touch "${{ runner.temp }}/devel-digests/${digest#sha256:}"
+
+      - name: Upload digest
+        uses: actions/upload-artifact@v4
+        with:
+          name: digests-${{ inputs.cann_tag }}-devel-${{ matrix.arch }}
+          path: ${{ runner.temp }}/devel-digests/*
+          if-no-files-found: error
+          retention-days: 1
+  
+  only-push-devel-image:
+    runs-on: ubuntu-latest
+    needs: only-build-push-devel-digest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
